
---
spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1 from dual
      validation-query-timeout: 30000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      stat-view-servlet:
        allow:
        deny:
        login-username: vincent
        login-password: h3Qjr/55itqRoUPp4OLGRQ==
        reset-enable: false
  main:
     allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
zk:
  serverList: 116.62.38.14:2181
  nameSpace: sms
